CREATE OR REPLACE VIEW employee_view AS
SELECT first_name, last_name
FROM employees;

SELECT * FROM EMPLOYEE_VIEW;

CREATE OR REPLACE VIEW employee_exp AS
SELECT first_name || ' ' || last_name, 
FLOOR(MONTHS_BETWEEN(CURRENT_DATE,HIRE_DATE) / 12)
experience 
FROM employees;

SELECT * FROM employee_exp;


CREATE OR REPLACE VIEW customerwithorder as
SELECT name, order_date, order 
FROM costomers inner join orders using (customer_id)
with read only;      


create table brand(
    brand_id number generated by default as identity primary key,
    brand_name varchar2(50) not null
);

insert into BRAND (BRAND_NAME)
values('toyoto');
insert into BRAND (brand_name)
values('bmw');
create or replace view brand_view as
select brand_id, brand_name from BRANDS;
update brand_view set brand_name='honda'
where brand_id=1;
delete from BRAND_view where brand_id=2;
select * from brands;
create index brand_index on brands (brand_name);